### SignUp

POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"username": "john_doe", "first_name": "John",
  "last_name": "Doe", "password": "Pass1234!", "email": "john@gmail.com"}

### LogIn

POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "john_doe", "password": "Pass1234!"}

### Test Token

GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706


### Logout
POST http://127.0.0.1:8000/logout/
Content-Type: application/json
Authorization: Token 23b16808f82e9a41d75fa6d7aabd9af79a5bee16


### Authenticated Orders

### Retrieve all orders (authenticated) ###
GET http://127.0.0.1:8000/orders/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

### Create a new order (authenticated) ###
POST http://127.0.0.1:8000/orders/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

{
  "order_number": "ORD002",
  "customer_name": "jane doe",
  "total_amount": 650.00,
  "is_completed": true
}

### Retrieve a specific order (authenticated) ###
GET http://127.0.0.1:8000/orders/1/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706 

### Update a specific order (authenticated) ###
PUT http://127.0.0.1:8000/orders/1/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706  

{
  "order_number": "ORD002",
  "customer_name": "John Doe",
  "total_amount": 150.00,
  "is_completed": true
}

### Delete a specific order (authenticated) ###
DELETE http://127.0.0.1:8000/orders/2/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706  

### Payment

### Retrieve all payments (authenticated) ###
GET http://127.0.0.1:8000/payments/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

### Create a new payment (authenticated) ###
POST http://127.0.0.1:8000/payments/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

{
  "order_id": 2, 
  "amount": 130.00,
  "transaction_id": "TXN001",
  "payment_method": "Credit Card"
}

### Retrieve a specific payment (authenticated) ###
GET http://127.0.0.1:8000/payments/1/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

### Update a specific payment (authenticated) ###
PUT http://127.0.0.1:8000/payments/1/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

{
  "order_id": 2, 
  "amount": 20.00,
  "transaction_id": "TXN002",
  "payment_method": "Credit Card"
}

### Delete a specific payment (authenticated) ###
DELETE http://127.0.0.1:8000/payments/1/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

### Notifications

### Retrieve all notifications (authenticated)

GET http://127.0.0.1:8000/notifications/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706


### Create a new notification (authenticated)

POST http://127.0.0.1:8000/notifications/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

{
  "recipient": "hemantjadhav.dev@gmail.com",
  "subject": "Welcome",
  "message": "Hello Hemant, welcome to our service!"
}



### Retrieve a specific notification (authenticated)

GET http://127.0.0.1:8000/notifications/4/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706


### Update a specific notification (authenticated)

PUT http://127.0.0.1:8000/notifications/2/
Content-Type: application/json
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706

{
  "recipient": "jane_doe@example.com",
  "subject": "Updated Subject",
  "message": "Hello Jane, this is an updated message."
}


### Delete a specific notification (authenticated)

DELETE http://127.0.0.1:8000/notifications/1/
Authorization: Token d1e4227ac2853c35d9030981c735f9dd15bff706